version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - type: bind
        source: ./secrets.env
        target: /app/secrets.env
        read_only: true
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - type: bind
        source: ./secrets.env
        target: /app/secrets.env
        read_only: true
    ports:
      - 8080:8080
    command: npm run serve  

  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    volumes:
      - ./blockchain/src:/app/src
      - type: bind
        source: ./secrets.env
        target: /app/secrets.env
        read_only: true
    ports:
      - 3000:3000
